@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTeamList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" UniqueChampionList
AddressBook *-right-> "1" UniqueRoleList
AddressBook *-right-> "1" UniqueRankList

UniquePersonList -[hidden]down- UniqueTeamList
UniqueTeamList -[hidden]down- UniqueTagList
UniqueTagList -[hidden]down- UniqueChampionList
UniqueChampionList -[hidden]down- UniqueRoleList
UniqueRoleList -[hidden]down- UniqueRankList

UniquePersonList -right-> "*" Person
UniqueTeamList -right-> "*" Team
UniqueTagList -right-> "*" Tag
UniqueChampionList -right-> "*" Champion
UniqueRoleList -right-> "*" Role
UniqueRankList -right-> "*" Rank

Person *--> "1" Name
Person *--> "1" Stats

Person -up-> "*" Tag
Person -up-> "1" Champion
Person -up-> "1" Role
Person -up-> "1" Rank

Team -up-> "5" Person

@enduml
