@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-down-> "1" UniqueTeamList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> "*" Person
UniqueTeamList -down-> "*" Team

Person -up-> "*" Tag

Person *--> "1" Name
Person *--> "1" Role
Person *--> "1" Rank
Person *--> "1" Champion

Team *--> "5" Person
@enduml
