@startuml
!include style.puml
skinparam participantStyle Rectangle
skinparam shadowing false

participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "descriptor:FilterPersonDescriptor" as Descriptor LOGIC_COLOR
participant ":FilterCommand" as FilterCommand LOGIC_COLOR

-> FilterCommandParser
activate FilterCommandParser
create Descriptor
FilterCommandParser -> Descriptor : FilterPersonDescriptor()
activate Descriptor
Descriptor --> FilterCommandParser
deactivate Descriptor

FilterCommandParser -> FilterCommandParser : parseRanksForFilter()
FilterCommandParser -> Descriptor : setRanks(Set<Rank>)
activate Descriptor
Descriptor --> FilterCommandParser
deactivate Descriptor

FilterCommandParser -> FilterCommandParser : parseRolesForFilter()
FilterCommandParser -> Descriptor : setRoles(Set<Role>)
activate Descriptor
Descriptor --> FilterCommandParser
deactivate Descriptor

FilterCommandParser -> FilterCommandParser : parseChampionsForFilter()
FilterCommandParser -> Descriptor : setChampions(Set<Champion>)
activate Descriptor
Descriptor --> FilterCommandParser
deactivate Descriptor

create FilterCommand
FilterCommandParser -> FilterCommand : FilterCommand(descriptor)
activate FilterCommand
FilterCommand --> FilterCommandParser
deactivate FilterCommand
<-- FilterCommandParser
deactivate FilterCommandParser
@enduml
