@startuml
!include style.puml
skinparam participantStyle Rectangle
skinparam shadowing false
skinparam sequenceReferenceBackgroundColor white

actor User
participant ":UI" as UI LOGIC_COLOR
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "descriptor:FilterPersonDescriptor" as Descriptor LOGIC_COLOR
participant ":FilterCommand" as FilterCommand LOGIC_COLOR
participant "m:Model" as Model LOGIC_COLOR


User -> UI : enter "filter rk/Diamond c/Yasuo"
activate UI
UI -> LogicManager : execute(cmdText)
activate LogicManager
LogicManager -> AddressBookParser : parseCommand(cmdText)
activate AddressBookParser
AddressBookParser -> FilterCommandParser : parse(args)
activate FilterCommandParser
create Descriptor
FilterCommandParser -> Descriptor : FilterPersonDescriptor()
activate Descriptor
ref over FilterCommandParser, Descriptor: Setting up parameters for FilterPersonDescriptor object: descriptor
Descriptor --> FilterCommandParser
deactivate Descriptor
create FilterCommand
FilterCommandParser -> FilterCommand : FilterCommand(descriptor)

activate FilterCommand
FilterCommand --> FilterCommandParser
deactivate FilterCommand
FilterCommandParser --> AddressBookParser
deactivate FilterCommandParser
AddressBookParser --> LogicManager : FilterCommand
deactivate AddressBookParser

LogicManager -> FilterCommand : execute(model)
activate FilterCommand
FilterCommand -> Model : updateFilteredPersonList(predicates)
activate Model
Model --> FilterCommand : filtered list updated
deactivate Model
FilterCommand --> LogicManager : CommandResult
deactivate FilterCommand
LogicManager --> UI : CommandResult
deactivate LogicManager
UI --> User : render filtered list
deactivate UI
@enduml
