@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant "v:ViewCommand" as ViewCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":PersonDetailWindow" as PersonDetailWindow UI_COLOR
end box

[-> ViewCommand : execute(m)
activate ViewCommand

ViewCommand -> Model : getFilteredPersonList()
activate Model

Model --> ViewCommand : personList
deactivate Model

ViewCommand -> ViewCommand : get person at index

create CommandResult
ViewCommand -> CommandResult : showPersonDetail(message, person)
activate CommandResult

CommandResult --> ViewCommand
deactivate CommandResult

[<-- ViewCommand : r
deactivate ViewCommand

[-> MainWindow : executeCommand()
activate MainWindow

MainWindow -> MainWindow : isShowPersonDetail()

MainWindow -> MainWindow : getPersonToShow()

create PersonDetailWindow
MainWindow -> PersonDetailWindow
activate PersonDetailWindow

PersonDetailWindow --> MainWindow
deactivate PersonDetailWindow

MainWindow -> PersonDetailWindow : setPerson(person)
activate PersonDetailWindow

PersonDetailWindow -> PersonDetailWindow : displayPersonDetails()
PersonDetailWindow -> PersonDetailWindow : displayCharts()

PersonDetailWindow --> MainWindow
deactivate PersonDetailWindow

MainWindow -> PersonDetailWindow : show()
activate PersonDetailWindow

PersonDetailWindow --> MainWindow
deactivate PersonDetailWindow

[<-- MainWindow
deactivate MainWindow

@enduml
